DROP ALL OBJECTS;

CREATE TABLE BATCH_PERSONNE (
   

    NOM VARCHAR(255) NOT NULL,
    PRENOM VARCHAR(255) NOT NULL,
    AGE VARCHAR(3) NOT NULL,
   
    PRIMARY KEY(NOM)
);


CREATE INDEX BATCH_NOM ON BATCH_PERSONNE (NOM ASC);
